// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScnProtobuf.proto

package com.wajam.scn.protobuf;

public final class ScnProtobuf {
  private ScnProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PTransportOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .com.wajam.scn.protobuf.PTransport.Type type = 1;
    boolean hasType();
    com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type getType();
    
    // repeated .com.wajam.scn.protobuf.PSequenceRange sequenceRanges = 2;
    java.util.List<com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange> 
        getSequenceRangesList();
    com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange getSequenceRanges(int index);
    int getSequenceRangesCount();
    java.util.List<? extends com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder> 
        getSequenceRangesOrBuilderList();
    com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder getSequenceRangesOrBuilder(
        int index);
  }
  public static final class PTransport extends
      com.google.protobuf.GeneratedMessage
      implements PTransportOrBuilder {
    // Use PTransport.newBuilder() to construct.
    private PTransport(Builder builder) {
      super(builder);
    }
    private PTransport(boolean noInit) {}
    
    private static final PTransport defaultInstance;
    public static PTransport getDefaultInstance() {
      return defaultInstance;
    }
    
    public PTransport getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PTransport_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PTransport_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      Empty(0, 1),
      ListSequenceRange(1, 2),
      ;
      
      public static final int Empty_VALUE = 1;
      public static final int ListSequenceRange_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return Empty;
          case 2: return ListSequenceRange;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.wajam.scn.protobuf.ScnProtobuf.PTransport.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        Empty, ListSequenceRange, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.wajam.scn.protobuf.PTransport.Type)
    }
    
    private int bitField0_;
    // optional .com.wajam.scn.protobuf.PTransport.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type getType() {
      return type_;
    }
    
    // repeated .com.wajam.scn.protobuf.PSequenceRange sequenceRanges = 2;
    public static final int SEQUENCERANGES_FIELD_NUMBER = 2;
    private java.util.List<com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange> sequenceRanges_;
    public java.util.List<com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange> getSequenceRangesList() {
      return sequenceRanges_;
    }
    public java.util.List<? extends com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder> 
        getSequenceRangesOrBuilderList() {
      return sequenceRanges_;
    }
    public int getSequenceRangesCount() {
      return sequenceRanges_.size();
    }
    public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange getSequenceRanges(int index) {
      return sequenceRanges_.get(index);
    }
    public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder getSequenceRangesOrBuilder(
        int index) {
      return sequenceRanges_.get(index);
    }
    
    private void initFields() {
      type_ = com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type.Empty;
      sequenceRanges_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      for (int i = 0; i < sequenceRanges_.size(); i++) {
        output.writeMessage(2, sequenceRanges_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      for (int i = 0; i < sequenceRanges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, sequenceRanges_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PTransport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wajam.scn.protobuf.ScnProtobuf.PTransport prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wajam.scn.protobuf.ScnProtobuf.PTransportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PTransport_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PTransport_fieldAccessorTable;
      }
      
      // Construct using com.wajam.scn.protobuf.ScnProtobuf.PTransport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSequenceRangesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type.Empty;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (sequenceRangesBuilder_ == null) {
          sequenceRanges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          sequenceRangesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wajam.scn.protobuf.ScnProtobuf.PTransport.getDescriptor();
      }
      
      public com.wajam.scn.protobuf.ScnProtobuf.PTransport getDefaultInstanceForType() {
        return com.wajam.scn.protobuf.ScnProtobuf.PTransport.getDefaultInstance();
      }
      
      public com.wajam.scn.protobuf.ScnProtobuf.PTransport build() {
        com.wajam.scn.protobuf.ScnProtobuf.PTransport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wajam.scn.protobuf.ScnProtobuf.PTransport buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wajam.scn.protobuf.ScnProtobuf.PTransport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wajam.scn.protobuf.ScnProtobuf.PTransport buildPartial() {
        com.wajam.scn.protobuf.ScnProtobuf.PTransport result = new com.wajam.scn.protobuf.ScnProtobuf.PTransport(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (sequenceRangesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            sequenceRanges_ = java.util.Collections.unmodifiableList(sequenceRanges_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.sequenceRanges_ = sequenceRanges_;
        } else {
          result.sequenceRanges_ = sequenceRangesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wajam.scn.protobuf.ScnProtobuf.PTransport) {
          return mergeFrom((com.wajam.scn.protobuf.ScnProtobuf.PTransport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wajam.scn.protobuf.ScnProtobuf.PTransport other) {
        if (other == com.wajam.scn.protobuf.ScnProtobuf.PTransport.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (sequenceRangesBuilder_ == null) {
          if (!other.sequenceRanges_.isEmpty()) {
            if (sequenceRanges_.isEmpty()) {
              sequenceRanges_ = other.sequenceRanges_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSequenceRangesIsMutable();
              sequenceRanges_.addAll(other.sequenceRanges_);
            }
            onChanged();
          }
        } else {
          if (!other.sequenceRanges_.isEmpty()) {
            if (sequenceRangesBuilder_.isEmpty()) {
              sequenceRangesBuilder_.dispose();
              sequenceRangesBuilder_ = null;
              sequenceRanges_ = other.sequenceRanges_;
              bitField0_ = (bitField0_ & ~0x00000002);
              sequenceRangesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSequenceRangesFieldBuilder() : null;
            } else {
              sequenceRangesBuilder_.addAllMessages(other.sequenceRanges_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type value = com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder subBuilder = com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSequenceRanges(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .com.wajam.scn.protobuf.PTransport.Type type = 1;
      private com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type type_ = com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type.Empty;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type getType() {
        return type_;
      }
      public Builder setType(com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.wajam.scn.protobuf.ScnProtobuf.PTransport.Type.Empty;
        onChanged();
        return this;
      }
      
      // repeated .com.wajam.scn.protobuf.PSequenceRange sequenceRanges = 2;
      private java.util.List<com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange> sequenceRanges_ =
        java.util.Collections.emptyList();
      private void ensureSequenceRangesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          sequenceRanges_ = new java.util.ArrayList<com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange>(sequenceRanges_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder> sequenceRangesBuilder_;
      
      public java.util.List<com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange> getSequenceRangesList() {
        if (sequenceRangesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sequenceRanges_);
        } else {
          return sequenceRangesBuilder_.getMessageList();
        }
      }
      public int getSequenceRangesCount() {
        if (sequenceRangesBuilder_ == null) {
          return sequenceRanges_.size();
        } else {
          return sequenceRangesBuilder_.getCount();
        }
      }
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange getSequenceRanges(int index) {
        if (sequenceRangesBuilder_ == null) {
          return sequenceRanges_.get(index);
        } else {
          return sequenceRangesBuilder_.getMessage(index);
        }
      }
      public Builder setSequenceRanges(
          int index, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange value) {
        if (sequenceRangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSequenceRangesIsMutable();
          sequenceRanges_.set(index, value);
          onChanged();
        } else {
          sequenceRangesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSequenceRanges(
          int index, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder builderForValue) {
        if (sequenceRangesBuilder_ == null) {
          ensureSequenceRangesIsMutable();
          sequenceRanges_.set(index, builderForValue.build());
          onChanged();
        } else {
          sequenceRangesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSequenceRanges(com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange value) {
        if (sequenceRangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSequenceRangesIsMutable();
          sequenceRanges_.add(value);
          onChanged();
        } else {
          sequenceRangesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSequenceRanges(
          int index, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange value) {
        if (sequenceRangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSequenceRangesIsMutable();
          sequenceRanges_.add(index, value);
          onChanged();
        } else {
          sequenceRangesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSequenceRanges(
          com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder builderForValue) {
        if (sequenceRangesBuilder_ == null) {
          ensureSequenceRangesIsMutable();
          sequenceRanges_.add(builderForValue.build());
          onChanged();
        } else {
          sequenceRangesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSequenceRanges(
          int index, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder builderForValue) {
        if (sequenceRangesBuilder_ == null) {
          ensureSequenceRangesIsMutable();
          sequenceRanges_.add(index, builderForValue.build());
          onChanged();
        } else {
          sequenceRangesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSequenceRanges(
          java.lang.Iterable<? extends com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange> values) {
        if (sequenceRangesBuilder_ == null) {
          ensureSequenceRangesIsMutable();
          super.addAll(values, sequenceRanges_);
          onChanged();
        } else {
          sequenceRangesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSequenceRanges() {
        if (sequenceRangesBuilder_ == null) {
          sequenceRanges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          sequenceRangesBuilder_.clear();
        }
        return this;
      }
      public Builder removeSequenceRanges(int index) {
        if (sequenceRangesBuilder_ == null) {
          ensureSequenceRangesIsMutable();
          sequenceRanges_.remove(index);
          onChanged();
        } else {
          sequenceRangesBuilder_.remove(index);
        }
        return this;
      }
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder getSequenceRangesBuilder(
          int index) {
        return getSequenceRangesFieldBuilder().getBuilder(index);
      }
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder getSequenceRangesOrBuilder(
          int index) {
        if (sequenceRangesBuilder_ == null) {
          return sequenceRanges_.get(index);  } else {
          return sequenceRangesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder> 
           getSequenceRangesOrBuilderList() {
        if (sequenceRangesBuilder_ != null) {
          return sequenceRangesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sequenceRanges_);
        }
      }
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder addSequenceRangesBuilder() {
        return getSequenceRangesFieldBuilder().addBuilder(
            com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.getDefaultInstance());
      }
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder addSequenceRangesBuilder(
          int index) {
        return getSequenceRangesFieldBuilder().addBuilder(
            index, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.getDefaultInstance());
      }
      public java.util.List<com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder> 
           getSequenceRangesBuilderList() {
        return getSequenceRangesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder> 
          getSequenceRangesFieldBuilder() {
        if (sequenceRangesBuilder_ == null) {
          sequenceRangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder, com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder>(
                  sequenceRanges_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          sequenceRanges_ = null;
        }
        return sequenceRangesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.wajam.scn.protobuf.PTransport)
    }
    
    static {
      defaultInstance = new PTransport(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.wajam.scn.protobuf.PTransport)
  }
  
  public interface PSequenceRangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 to = 1;
    boolean hasTo();
    long getTo();
    
    // optional uint64 from = 2;
    boolean hasFrom();
    long getFrom();
  }
  public static final class PSequenceRange extends
      com.google.protobuf.GeneratedMessage
      implements PSequenceRangeOrBuilder {
    // Use PSequenceRange.newBuilder() to construct.
    private PSequenceRange(Builder builder) {
      super(builder);
    }
    private PSequenceRange(boolean noInit) {}
    
    private static final PSequenceRange defaultInstance;
    public static PSequenceRange getDefaultInstance() {
      return defaultInstance;
    }
    
    public PSequenceRange getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PSequenceRange_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PSequenceRange_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 to = 1;
    public static final int TO_FIELD_NUMBER = 1;
    private long to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTo() {
      return to_;
    }
    
    // optional uint64 from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private long from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getFrom() {
      return from_;
    }
    
    private void initFields() {
      to_ = 0L;
      from_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, to_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, from_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, to_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, from_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wajam.scn.protobuf.ScnProtobuf.PSequenceRangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PSequenceRange_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wajam.scn.protobuf.ScnProtobuf.internal_static_com_wajam_scn_protobuf_PSequenceRange_fieldAccessorTable;
      }
      
      // Construct using com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        to_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.getDescriptor();
      }
      
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange getDefaultInstanceForType() {
        return com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.getDefaultInstance();
      }
      
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange build() {
        com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange buildPartial() {
        com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange result = new com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange) {
          return mergeFrom((com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange other) {
        if (other == com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.getDefaultInstance()) return this;
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              to_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              from_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 to = 1;
      private long to_ ;
      public boolean hasTo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTo() {
        return to_;
      }
      public Builder setTo(long value) {
        bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 from = 2;
      private long from_ ;
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getFrom() {
        return from_;
      }
      public Builder setFrom(long value) {
        bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.wajam.scn.protobuf.PSequenceRange)
    }
    
    static {
      defaultInstance = new PSequenceRange(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.wajam.scn.protobuf.PSequenceRange)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wajam_scn_protobuf_PTransport_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wajam_scn_protobuf_PTransport_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wajam_scn_protobuf_PSequenceRange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wajam_scn_protobuf_PSequenceRange_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ScnProtobuf.proto\022\026com.wajam.scn.proto" +
      "buf\"\255\001\n\nPTransport\0225\n\004type\030\001 \001(\0162\'.com.w" +
      "ajam.scn.protobuf.PTransport.Type\022>\n\016seq" +
      "uenceRanges\030\002 \003(\0132&.com.wajam.scn.protob" +
      "uf.PSequenceRange\"(\n\004Type\022\t\n\005Empty\020\001\022\025\n\021" +
      "ListSequenceRange\020\002\"*\n\016PSequenceRange\022\n\n" +
      "\002to\030\001 \001(\004\022\014\n\004from\030\002 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wajam_scn_protobuf_PTransport_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wajam_scn_protobuf_PTransport_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wajam_scn_protobuf_PTransport_descriptor,
              new java.lang.String[] { "Type", "SequenceRanges", },
              com.wajam.scn.protobuf.ScnProtobuf.PTransport.class,
              com.wajam.scn.protobuf.ScnProtobuf.PTransport.Builder.class);
          internal_static_com_wajam_scn_protobuf_PSequenceRange_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_wajam_scn_protobuf_PSequenceRange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wajam_scn_protobuf_PSequenceRange_descriptor,
              new java.lang.String[] { "To", "From", },
              com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.class,
              com.wajam.scn.protobuf.ScnProtobuf.PSequenceRange.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
